# Generated by Django 6.0.4 on 2026-04-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_learningmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
