# Generated by Django 6.0.4 on 2026-04-23 06:54

from django.db import migrations, models

def gen_unique_codes(apps, schema_editor):
    Course = apps.get_model('school', 'Course')
    for i, course in enumerate(Course.objects.filter(course_code__isnull=True)):
        course.course_code = f"temp-{course.id}-{i}"
        course.save()

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_course_code'),
    ]

    operations = [
        migrations.RunPython(gen_unique_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='temp-code', max_length=20, unique=True),
        ),
    ]
