# Generated by Django 6.0.5 on 2026-05-27 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.AddField(
            model_name='payment',
            name='dadate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
