# Generated by Django 6.0.5 on 2026-05-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_payment_date_payment_dadate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='dadate',
            new_name='date',
        ),
    ]
