# Generated by Django 6.0.4 on 2026-06-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_attendance'),
        ('school', '0008_rename_dadate_payment_date'),
    ]

    operations = [
    ]
